# tmux内部のTERM
set -g default-terminal "tmux-256color"

# True Color
set -as terminal-features ",alacritty:RGB"
set -as terminal-features ",xterm-kitty:RGB"

# Clipboard / OSC52
set -as terminal-features ",alacritty:clipboard"
set -as terminal-features ",xterm-kitty:clipboard"

# SSH先のNeovimなどからOSC52でclipboardへ送れるようにする
set -s set-clipboard on

# 基本設定
set -g mouse on
set -g history-limit 100000
set -g renumber-windows on
set -g focus-events on

# viライク
setw -g mode-keys vi

# 1始まり
set -g base-index 1
setw -g pane-base-index 1

# NeovimでEscの遅延を減らす
set -sg escape-time 10
