[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
padding = { x = 12, y = 12 }
opacity = 0.65
decorations = "None"

[cursor]
# "Block", "Underline"
style = { shape = "Beam", blinking = "Off" }

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  # { key = "C", mods = "Control|Shift", action = "Copy" },
  # { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "-", mods = "Control|Shift", action = "DecreaseFontSize" },
]

# [terminal]
# osc52 = "CopyPaste"
