[ids]
*

[main]
leftmeta = layer(meta_mac)

[meta_mac:C]
c = C-insert # c = C-S-c
v = S-insert # v = C-S-v 
x = S-delete
z = C-z
S-z = C-S-z

left = home
right = end
up = C-home
down = C-end

# niri設定側でAlt Spaceでlancher起動
# zmk側でlayer + EnterをAlt Spaceにしている
space = A-space
